bibliotheque_locale/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add paths from the gestion application 
from django.urls import include
from django.urls import path

urlpatterns += [
    path('gestion/', include('gestion.urls')),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/gestion/', permanent=True)),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestion/urls.py
####### Ce fichier définit les URLs propres à notre application "gestion"

from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('ouvrage/', views.OuvrageListView.as_view(), name='ouvrage'),
    path('ouvrage/<int:pk>', views.OuvrageDetailView.as_view(), name='ouvrage-detail'),
    path('auteur/', views.AuteurListView.as_view(), name='auteur'),
    path('auteur/<int:pk>', views.AuteurDetailView.as_view(), name='auteur-detail'),
    path('genre/', views.GenreListView.as_view(), name='genre'),
    path('genre/<int:pk>', views.GenreDetailView.as_view(), name='genre-detail'),
    path('tarifs/', views.TarifListView.as_view(), name='tarif')
]

urlpatterns += [   
    path('mon_compte/', views.MonCompteListView.as_view(), name='mon_compte'),
]

gestion/models.py
####### Ce fichier définit les modèles de données (différentes tables) utilisées par notre projet

from django.db import models
from django.urls import reverse

from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser

from datetime import datetime, timezone, timedelta

import uuid



class Profile(models.Model):
    nb_livres = models.IntegerField(default=0)
    nb_autres = models.IntegerField(default=0)

    nb_retards = models.IntegerField(default=0)
    premier_retard = models.DateTimeField(null=True, blank=True, default=None)
    deuxième_retard = models.DateTimeField(null=True, blank=True, default=None)
    troisième_retard = models.DateTimeField(null=True, blank=True, default=None)


    BOOL_CHOICE = (
        (0, 0),
        (1, 1)
    )
    bad_user = models.IntegerField(default=0, choices=BOOL_CHOICE)
    
    
    date_bad_user = models.DateTimeField(null=True, blank=True, default=None)

    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, blank=True, unique=True)

    STATUT_TYPE = (
        ('e', 'Étudiant'),
        ('c', 'En recherche d\'emploi'),
        ('r', 'Retraité'),
        ('f', 'Moins de 18 ans'),
        ('a', 'Adulte sans réduction')
    )

    statut = models.CharField(
        max_length=1,
        choices=STATUT_TYPE,
        blank=True,
        help_text='Statut de l\'abonné',
    )

    def __str__(self):
        """Fonction requise par Django pour manipuler les objets Ouvrages dans la base de données."""
        return self.user.username

    @property # property?
    def check_bad_user(self):
        durée_premier_retard = (datetime.now(timezone.utc).date() - self.premier_retard)
        if (durée_premier_retard < timedelta(days=365)) and (self.nb_retards > 3):
            return True
        return False

    # def reset_retards(self):
    #     durée_premier_retard = (date.today() - self.premier_retard)
    #     if (durée_premier_retard > timedelta(days=365)) and user.is_overdue == True:
    #         self.premier_retard = date.today()


class Auteur(models.Model):
    nom = models.CharField(max_length=100)
    prénom = models.CharField(max_length=100)
    lien = models.CharField(max_length=100, default=None, blank=True, null=True)
    img = models.ImageField(upload_to='img/', verbose_name='Photo de l\'auteur', blank=True, null=True)

    YEAR_CHOICES = [(r,r) for r in range(1800, datetime.now(timezone.utc).date().year+1)]

    naissance = models.IntegerField(('Naissance:'), choices=YEAR_CHOICES, default=datetime.now(timezone.utc).date().year)
    mort = models.IntegerField(('Mort:'), choices=YEAR_CHOICES, default=None, null=True, blank=True)

    def __str__(self):
        """Fonction requise par Django pour manipuler les objets Ouvrages dans la base de données."""
        return f'{self.nom}, {self.prénom}'

    def get_absolute_url(self):
        """Cette fonction est requise pas Django, lorsque vous souhaitez détailler le contenu d'un objet."""
        return reverse('auteur-detail', args=[str(self.id)])


class Genre(models.Model):
    titre = models.CharField(max_length=100, help_text='Entrer le genre de l\'ouvrage (e.g. Science Fiction)')

    def __str__(self):
        return self.titre

    def get_absolute_url(self):
        return reverse('genre-detail', args=[str(self.id)])


class Ouvrage(models.Model):
    titre = models.CharField(max_length=100)
    nb_copies = models.IntegerField(default=1)

    BOOL_CHOICE = (
        (0, 0),
        (1, 1)
    )

    autorisé = models.IntegerField(default=1, choices=BOOL_CHOICE)

    OUVRAGES_TYPE = (
        ('r', 'Revue'),
        ('d', 'DVD'),
        ('v', 'Vinyl'),
        ('l', 'Livre'),
        ('c', 'CD')
    )


    type =  models.CharField(
        max_length=1,
        choices=OUVRAGES_TYPE,
        blank=True,
        help_text='Type d\'ouvrage',
    )


    YEAR_CHOICES = [(r,r) for r in range(1800, datetime.now(timezone.utc).date().year+1)]

    année = models.IntegerField(('année'), choices=YEAR_CHOICES, default=datetime.now(timezone.utc).date().year)


    auteur = models.ForeignKey(Auteur, on_delete=models.SET_NULL, null=True)
    genre = models.ManyToManyField(Genre, help_text='Selectionner un genre pour cet ouvrage')

    def __str__(self):
        """Fonction requise par Django pour manipuler les objets Ouvrages dans la base de données."""
        return self.titre

    def get_absolute_url(self):
        """Cette fonction est requise pas Django, lorsque vous souhaitez détailler le contenu d'un objet."""
        return reverse('ouvrage-detail', args=[str(self.id)])

    def update_copies(self):
        self.nb_copies -= 1

    # def save(self, *args, **kwargs):
    #     self.update_copies()
    #     super(Ouvrage, self).save(*args, **kwargs) 



class EmpruntQuerySet(models.QuerySet):
    """ permet de gérer les multiples delete """

    def delete(self, *args, **kwargs):
        for obj in self:
            obj.delete()
        super(EmpruntQuerySet, self).delete(*args, **kwargs)

class Emprunt(models.Model):
    objects = EmpruntQuerySet.as_manager()
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID pour cet emprunt')
    date_emprunt = models.DateTimeField()

    BOOL_CHOICE = (
        (0, 0),
        (1, 1)
    )

    retard = models.IntegerField(default=0, choices=BOOL_CHOICE)
    pénalité = models.IntegerField(default=0)

    ouvrage = models.ForeignKey(Ouvrage, on_delete=models.SET_NULL, null=True)
    borrower = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)

    class Meta:
        permissions = (("can_mark_returned", "Set book as returned"),)

    def __str__(self):
        """Fonction requise par Django pour manipuler les objets Ouvrages dans la base de données."""
        return f'{self.id} ({self.ouvrage.titre})'


    ## Triggers:
    def save(self, *args, **kwargs):
        
        def diminue_copie():
            ## Descend le nombre de copies de 1
            if self.ouvrage.nb_copies > 0:
                new_nb_copies = self.ouvrage.nb_copies - 1
                Ouvrage.objects.filter(id=self.ouvrage.id).update(nb_copies = new_nb_copies)
                print(self.ouvrage.titre, "emprunté avec succès.")
                super(Emprunt, self).save(*args, **kwargs)
            else:
                print("Impossible à emprunter. Il n'y a plus de copies disponibles.")
                pass

        ## Incrémente le nombre de livres de Profile, et diminue le nombre de copie

        if (self.ouvrage.autorisé == 1) and (self.borrower.bad_user == 0):
            if self.ouvrage.type == 'l':
                if self.borrower.nb_livres < 3:
                    new_nb_livres = self.borrower.nb_livres + 1
                    Profile.objects.filter(id=self.borrower.id).update(nb_livres = new_nb_livres)
                    diminue_copie()
                else:
                    print("Impossible à emprunter. Trop de livres déjà empruntés.")
            else:
                if self.borrower.nb_autres < 2:
                    new_nb_autres = self.borrower.nb_autres + 1
                    Profile.objects.filter(id=self.borrower.id).update(nb_autres = new_nb_autres)
                    diminue_copie()
                else:
                    print("Impossible à emprunter. Trop d'oeuvres de type DVD/CD/Vinyl déjà empruntées.")
        elif (self.borrower.bad_user == 1):
            print("Impossible à emprunter. Vous êtes blacklisté.")
        else:
            print("Impossible à emprunter. Cette oeuvre n'est pas autorisé au prêt.")


    def delete(self, *args, **kwargs):

        def augmente_copie():
            ## Augmente le nombre de copies de 1
            new_nb_copies = self.ouvrage.nb_copies + 1
            Ouvrage.objects.filter(id=self.ouvrage.id).update(nb_copies = new_nb_copies)
            print(self.ouvrage.titre, "rendu avec succès.")
            super(Emprunt, self).delete(*args, **kwargs)

        ## Décrémente le nombre de livres de Profile, et augmente le nombre de copie

        if self.ouvrage.type == 'l':
            new_nb_livres = self.borrower.nb_livres - 1
            Profile.objects.filter(id=self.borrower.id).update(nb_livres = new_nb_livres)
            augmente_copie()
           
        else:
            new_nb_autres = self.borrower.nb_autres - 1
            Profile.objects.filter(id=self.borrower.id).update(nb_autres = new_nb_autres)
            augmente_copie()



    ## Methods:
    def compute_date_retour(self):
        date_retour = self.date_emprunt + timedelta(weeks=+4)
        return date_retour

    def compute_pénalité(self):
        pénalité = (datetime.now(timezone.utc) - self.date_retour).days - 3
        if pénalité<0:
            pénalité = 0
        return pénalité

    ## Properties:

    @property
    def date_retour(self):
        return self.compute_date_retour()

    @property
    def pénalité_property(self):
        return self.compute_pénalité()
    
    @property
    def is_overdue(self):
        if self.date_retour and datetime.now(timezone.utc).date() > self.date_retour.date():
            return True
        return False


class Tarif(models.Model):

    STATUT_TYPE = (
        ('e', 'Étudiant'),
        ('c', 'En recherche d\'emploi'),
        ('r', 'Retraité'),
        ('f', 'Moins de 18 ans'),
        ('a', 'Adulte sans réduction')
    )

    statut = models.CharField(
        max_length=1,
        choices=STATUT_TYPE,
        blank=True,
        help_text='Statut de l\'abonné',
    )

    prix = models.IntegerField()

    def __str__(self):
        """Fonction requise par Django pour manipuler les objets Ouvrages dans la base de données."""
        return f'{self.statut} ({self.prix})'

gestion/views.py
####### Ce fichier est le fichier principal qui définit les actions que réalisent l'application lors du chargement
####### de chaque page (les 'vues').

from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from gestion.models import Ouvrage, Emprunt, Tarif, Auteur, Profile, Genre
from django.db.models import Avg, Count, Min, Sum

from django.shortcuts import get_object_or_404
from datetime import datetime, timezone, timedelta, date


## Fonction annexe

def update_and_populate_db(date_today):

    ''' Fonction qui, à chaque arrivée sur la page, met à jour le statut des retards et des pénalités'''


    # Met à jour les retards sur les emprunts
    for emp in Emprunt.objects.all():
        if emp.is_overdue:
            if emp.retard == 0:
                print("Un nouveau retard a été trouvé.")
                emp.retard = 1
                print("Augmentation du nombre de retard de l'utilisateur concerné.")
                if emp.borrower.nb_retards == 0:
                    emp.borrower.premier_retard = date_today
                if emp.borrower.nb_retards == 1:
                    emp.borrower.deuxième_retard = date_today
                if emp.borrower.nb_retards == 2:
                    emp.borrower.troisième_retard = date_today
                    emp.borrower.bad_user = 1
                    emp.borrower.date_bad_user = date_today
                emp.borrower.nb_retards = emp.borrower.nb_retards + 1
                emp.borrower.save()
            emp.pénalité = emp.pénalité_property
            super(Emprunt, emp).save()


    # Met à jour le nombre de retards sur les utiliateurs
    for brw in Profile.objects.all():

        ## Réinitialisation du statut de blacklisté

        if brw.bad_user == 1:
            date_fin_bad_user = brw.date_bad_user + timedelta(days=730)
            if date_today - date_fin_bad_user > timedelta(days=0):
                print("Fin de période de blacklist.")
                brw.bad_user = 0

        ## Réinitialisation des dates de retard

        if brw.premier_retard != None:
            if date_today - (brw.premier_retard + timedelta(days=365)) > timedelta(days=0):
                brw.premier_retard = brw.deuxième_retard
                brw.deuxième_retard = brw.troisième_retard
                brw.troisième_retard = None
                brw.nb_retards -= 1

        brw.save()


## Vues du site


def index(request):
    """Vue de la page d'accueil"""

    # Etat de la base de donnée
    date_today = datetime.now(timezone.utc)
    num_ouvrages = Ouvrage.objects.all().count()
    num_emprunts = Emprunt.objects.all().count()
    num_ouvrages_dispo = Ouvrage.objects.aggregate(Sum('nb_copies'))['nb_copies__sum']
    num_retard = Emprunt.objects.filter(retard = 1).all().count()
    num_en_regle = num_emprunts - num_retard


    # met à jour le statut des emprunts et des utilisateurs
    update_and_populate_db(date_today)

    # Nombre de visites de cette page
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1


    # met à jour le contexte
    context = {
        'date_today': date_today,
        'num_ouvrages': num_ouvrages,
        'num_emprunts': num_emprunts,
        'num_ouvrages_dispo': num_ouvrages_dispo,
        'num_visits': num_visits,
        'num_retard': num_retard,
        'num_en_regle': num_en_regle
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)



class OuvrageListView(generic.ListView):
    model = Ouvrage
    ordering = ["titre"]
    paginate_by = 10

class OuvrageDetailView(generic.DetailView):
    model = Ouvrage

class GenreListView(generic.ListView):
    ordering = ["titre"]
    model = Genre
    paginate_by = 10

class GenreDetailView(generic.DetailView):
    model = Genre

class AuteurListView(generic.ListView):
    ordering = ["nom"]
    model = Auteur
    paginate_by = 10

class TarifListView(generic.ListView):
    ordering = ["prix"]
    model = Tarif
    paginate_by = 10

class AuteurDetailView(generic.DetailView):
    model = Auteur

class MonCompteListView(LoginRequiredMixin,generic.ListView):
    """Generic class-based view """

    model = Emprunt
    template_name ='gestion/mon_compte.html'
    paginate_by = 10

    # méthodes de classes

    def get_queryset(self):

        connected_user = self.request.user
        connected_profile = Profile.objects.get(user=connected_user) ## NB : use get with user=xxx or filter with user__in=xxx selon si xxx est une queryset ou un object

        return Emprunt.objects.filter(borrower = connected_profile).order_by('date_emprunt')

    def get_context_data(self,**kwargs):

        # met à jour le statut des emprunts et des utilisateurs 
        date_today = datetime.now(timezone.utc)
        update_and_populate_db(date_today)

        connected_user = self.request.user
        connected_profile = Profile.objects.get(user=connected_user)

        context = super(MonCompteListView, self).get_context_data(**kwargs)
        context['bad_user'] = connected_profile.bad_user
        context['nb_livres'] = connected_profile.nb_livres
        context['nb_autres'] = connected_profile.nb_autres
        context['date'] = datetime.now(timezone.utc)
        context['nb_retards'] = connected_profile.nb_retards
        context['statut'] = connected_profile.get_statut_display
        if connected_profile.date_bad_user != None:
            context['date_fin_bad_user'] = connected_profile.date_bad_user + timedelta(days=730)
        return context

gestion/templates/gestion/auteur_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Auteur: {{ auteur.nom }}, {{ auteur.prénom }}</h1>
  <br>

  <p><strong>Naissance:</strong> {{ auteur.naissance }}</p> <!-- author detail link not yet defined --> 
  <p><strong>Mort:</strong> {{ auteur.mort }} </p> 
  <p><strong><a href={{ auteur.lien }}>Lien Wikipédia</a></strong></p>
  {% load static %}
  {% if auteur.img %}
    <img src="{{STATIC_URL}}{{ auteur.img.url }}" alt="" /> 
  {% else %}
    <p><i>Pas encore d'image pour cet auteur.</i>  </p> 
  {% endif %}
  <div style="margin-left:20px;margin-top:20px">
    <h4>Oeuvres de cet auteur :</h4>

    {% for ouvr in auteur.ouvrage_set.all %}
      <hr>
      <p><a href="{% url 'ouvrage-detail' ouvr.pk %}"> {{ouvr.titre}} ({{ouvr.année}}) [{{ouvr.get_type_display}}] </a> </p> 
      
    {% endfor %}
  </div>

{% endblock %}

gestion/templates/gestion/auteur_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Liste des auteurs</h1>
  <br>
  {% if auteur_list %}
  <ul>
    {% for auteur in auteur_list %}
      <li>
        <a href="{{ auteur.get_absolute_url }}">{{ auteur.nom }}, {{ auteur.prénom }} </a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Il n'y a pas d'auteurs enregistrés.</p>
  {% endif %}       
{% endblock %}

gestion/templates/gestion/genre_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Genre: {{ genre.titre }}</h1>
 <br>

 
  <div style="margin-left:20px;margin-top:20px">
    <h4>Oeuvres de ce genre :</h4>

    {% for ouvr in genre.ouvrage_set.all %}
      <hr>
      <p><a href="{% url 'ouvrage-detail' ouvr.pk %}"> {{ouvr.titre}} ({{ouvr.année}}) [{{ouvr.get_type_display}}] </a> </p> 

    {% endfor %}
  </div>



{% endblock %}

gestion/templates/gestion/genre_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Liste des genres</h1>
  <br>
  {% if genre_list %}
  <ul>
    {% for genre in genre_list %}
      <li>
        <a href="{{ genre.get_absolute_url }}">{{ genre.titre }}</a>  <!-- {{ genre.nb_ouvrage }} -->
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Il n'y a pas de genres enregistrés.</p>
  {% endif %}       
{% endblock %}

gestion/templates/gestion/mon_compte.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Mon compte</h1>

    

    <br>
    Bonjour, <b> {{ user.get_username }}. </b> 
    <br>
    Vous êtes actuellement abonné en tant que <b> {{ statut }}</b>.
    <br>
    {% if bad_user == 1 %} <p style="color:Red;"> Vous êtes actuellement blacklisté pour trop de retards jusqu'au <b> {{date_fin_bad_user}} </b> {% elif nb_autres == 2 and nb_livres == 3 %} <b style="color:Red;"> Vous avez atteint le nombre maximum d'emprunts. </b> {% else %} <b style="color:Green;"> Vous êtes autorisés à emprunter. </b> {% endif %} </p>
    <br>
    Nous sommes le <strong>{{ date }}</strong>

    {% if emprunt_list %}
    <p> Nombre de livres empruntés: <strong>{{ nb_livres }}/3</strong> | Nombre de médias empruntés: <strong>{{ nb_autres }}/2</strong> | Nombre de retards cette année: <strong style="color:Red;">{{ nb_retards }}/3</strong> </p>
    <ul>

      {% for emp in emprunt_list %} 
      <li>
        <a href="{% url 'ouvrage-detail' emp.ouvrage.pk %}">{{emp.ouvrage.titre}} ({{emp.ouvrage.get_type_display}})</a> 
        (<b>emprunté:</b> {{ emp.date_emprunt }}) <br>
        <b> Votre date de retour: </b> {{ emp.date_retour }}) | {% if emp.is_overdue %} <b style="color:Red;"> VOUS ÊTES EN RETARD ! Pénalité à payer dès que possible: {{ emp.pénalité }}€</b> {% else %} <b style="color:Green;"> Vous êtes en règle. </b> {% endif %}     
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <br>
      <p>Vous n'avez pas encore emprunté d'ouvrages.</p> 
    {% endif %}       
{% endblock %}

gestion/templates/gestion/ouvrage_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Titre: {{ ouvrage.titre }}</h1>
  <br>
  {% if ouvrage.autorisé == 1 %} <p style="color:Green;"><strong>Ouvrage autorisé au prêt</strong></p> {% else %} <p style="color:Red;"><strong>Ouvrage non autorisé au prêt</strong></p> {% endif %}
  <p><strong>Type:</strong> {{ouvrage.get_type_display}} </p>
  <p><strong>Auteur:</strong> <a href="{{ ouvrage.auteur.get_absolute_url }}">{{ ouvrage.auteur }}</a></p>
  <p><strong>Année:</strong> {{ ouvrage.année }} </p>
  <p><strong>Genres:</strong>  
  {% for g in ouvrage.genre.all %}
    <li> <a href="{{ g.get_absolute_url }}">{{ g.titre }}</a> </li>
  {% endfor %}
  <br>
  <p><strong>Nombre de copies restantes :</strong> {{ ouvrage.nb_copies }}</p>
  

  {% if user.get_username == "admin" %}

  <div style="margin-left:20px;margin-top:20px">

    <h4>Emprunts :</h4>

    {% for emp in ouvrage.emprunt_set.all %}
      <hr>
      <p class="text-muted"><strong>Emprunteur:</strong> {{emp.borrower}}</p>
      <p><strong>Devrait être retourné avant le {{ emp.date_retour }}</strong></p>

      {% if emp.nb_copies > 0 %}
        
      {% endif %}
      
      <p class="text-muted"><strong>Id:</strong> {{emp.ouvrage.id}}</p>
    {% endfor %}
  </div>

  {% endif %}
{% endblock %}

gestion/templates/gestion/ouvrage_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Liste des ouvrages</h1>
  <br>
  {% if ouvrage_list %}
  <ul>
    {% for ouvrage in ouvrage_list %}
      <li>
        <a href="{{ ouvrage.get_absolute_url }}">{{ ouvrage.titre }}</a> ({{ouvrage.auteur}} | {{ouvrage.année}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Il n'y a pas d'ouvrages dans la bibliothèque.</p>
  {% endif %}       
{% endblock %}

gestion/templates/gestion/tarif_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Tarifs actuellement en vigueur</h1>
  <br>
  {% if tarif_list %}
  <ul>
    {% for tarif in tarif_list %}
      <li> <b> {{ tarif.get_statut_display }} </b> : {{ tarif.prix }}€</li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Il n'y a pas de tarifs enregistrés.</p>
  {% endif %}       
{% endblock %}